name: Variable and Context

on: 
  workflow_dispatch:
    # inputs:
    #   name:
    #     description: "Person to greet"
    #     default: "World"
    #     required: true
    #     type: string

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  
